// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type CartItem struct {
	CartItemID int64   `json:"cart_item_id"`
	UserID     int64   `json:"user_id"`
	ProductID  int64   `json:"product_id"`
	Quantity   int64   `json:"quantity"`
	Price      float64 `json:"price"`
}

type Category struct {
	CategoryID int64  `json:"category_id"`
	Name       string `json:"name"`
}

type Order struct {
	OrderID     int64   `json:"order_id"`
	UserID      int64   `json:"user_id"`
	TotalAmount float64 `json:"total_amount"`
	// CHECK (status IN ('pending', 'completed'))
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type OrderItem struct {
	OrderItemID int64   `json:"order_item_id"`
	OrderID     int64   `json:"order_id"`
	ProductID   int64   `json:"product_id"`
	Quantity    int64   `json:"quantity"`
	Price       float64 `json:"price"`
}

type Payment struct {
	PaymentID     int64   `json:"payment_id"`
	OrderID       int64   `json:"order_id"`
	PaymentMethod string  `json:"payment_method"`
	Amount        float64 `json:"amount"`
	// CHECK (status IN ('pending', 'completed'))
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ProductID     int64     `json:"product_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	Price         float64   `json:"price"`
	StockQuantity int64     `json:"stock_quantity"`
	CategoryID    int64     `json:"category_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Review struct {
	ReviewID  int64 `json:"review_id"`
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	// CHECK (rating >= 1 AND rating <= 5)
	Rating    int64     `json:"rating"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	UserID       int64     `json:"user_id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Email        string    `json:"email"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}
