// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	ClearUserCart(ctx context.Context, userID int64) error
	CountUserProductOrders(ctx context.Context, arg CountUserProductOrdersParams) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecreaseProductStock(ctx context.Context, arg DecreaseProductStockParams) error
	DeleteCartItem(ctx context.Context, cartItemID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetCartItemByUserAndProduct(ctx context.Context, arg GetCartItemByUserAndProductParams) (CartItem, error)
	GetCartItemsByUser(ctx context.Context, userID int64) ([]CartItem, error)
	GetCategory(ctx context.Context, categoryID int64) (Category, error)
	GetOrder(ctx context.Context, orderID int64) (Order, error)
	GetPaymentByOrder(ctx context.Context, orderID int64) (Payment, error)
	GetProduct(ctx context.Context, productID int64) (Product, error)
	GetProductForUpdate(ctx context.Context, productID int64) (Product, error)
	GetReviewsForProduct(ctx context.Context, productID int64) ([]Review, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListOrdersByUser(ctx context.Context, userID int64) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID int64) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
