// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: rpc_create_product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*CreateProductRequest_Info
	//	*CreateProductRequest_ImageChunk
	Data          isCreateProductRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_rpc_create_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetData() isCreateProductRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateProductRequest) GetInfo() *ProductInfo {
	if x != nil {
		if x, ok := x.Data.(*CreateProductRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *CreateProductRequest) GetImageChunk() *ImageChunk {
	if x != nil {
		if x, ok := x.Data.(*CreateProductRequest_ImageChunk); ok {
			return x.ImageChunk
		}
	}
	return nil
}

type isCreateProductRequest_Data interface {
	isCreateProductRequest_Data()
}

type CreateProductRequest_Info struct {
	Info *ProductInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type CreateProductRequest_ImageChunk struct {
	ImageChunk *ImageChunk `protobuf:"bytes,2,opt,name=image_chunk,json=imageChunk,proto3,oneof"`
}

func (*CreateProductRequest_Info) isCreateProductRequest_Data() {}

func (*CreateProductRequest_ImageChunk) isCreateProductRequest_Data() {}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_rpc_create_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_rpc_create_product_proto protoreflect.FileDescriptor

const file_rpc_create_product_proto_rawDesc = "" +
	"\n" +
	"\x18rpc_create_product.proto\x12\x02pb\x1a\rproduct.proto\"x\n" +
	"\x14CreateProductRequest\x12%\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.pb.ProductInfoH\x00R\x04info\x121\n" +
	"\vimage_chunk\x18\x02 \x01(\v2\x0e.pb.ImageChunkH\x00R\n" +
	"imageChunkB\x06\n" +
	"\x04data\"X\n" +
	"\x15CreateProductResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\aproduct\x18\x02 \x01(\v2\v.pb.ProductR\aproductB\x1aZ\x18github.com/e-commerce/pbb\x06proto3"

var (
	file_rpc_create_product_proto_rawDescOnce sync.Once
	file_rpc_create_product_proto_rawDescData []byte
)

func file_rpc_create_product_proto_rawDescGZIP() []byte {
	file_rpc_create_product_proto_rawDescOnce.Do(func() {
		file_rpc_create_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_product_proto_rawDesc), len(file_rpc_create_product_proto_rawDesc)))
	})
	return file_rpc_create_product_proto_rawDescData
}

var file_rpc_create_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_product_proto_goTypes = []any{
	(*CreateProductRequest)(nil),  // 0: pb.CreateProductRequest
	(*CreateProductResponse)(nil), // 1: pb.CreateProductResponse
	(*ProductInfo)(nil),           // 2: pb.ProductInfo
	(*ImageChunk)(nil),            // 3: pb.ImageChunk
	(*Product)(nil),               // 4: pb.Product
}
var file_rpc_create_product_proto_depIdxs = []int32{
	2, // 0: pb.CreateProductRequest.info:type_name -> pb.ProductInfo
	3, // 1: pb.CreateProductRequest.image_chunk:type_name -> pb.ImageChunk
	4, // 2: pb.CreateProductResponse.product:type_name -> pb.Product
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_create_product_proto_init() }
func file_rpc_create_product_proto_init() {
	if File_rpc_create_product_proto != nil {
		return
	}
	file_product_proto_init()
	file_rpc_create_product_proto_msgTypes[0].OneofWrappers = []any{
		(*CreateProductRequest_Info)(nil),
		(*CreateProductRequest_ImageChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_product_proto_rawDesc), len(file_rpc_create_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_product_proto_goTypes,
		DependencyIndexes: file_rpc_create_product_proto_depIdxs,
		MessageInfos:      file_rpc_create_product_proto_msgTypes,
	}.Build()
	File_rpc_create_product_proto = out.File
	file_rpc_create_product_proto_goTypes = nil
	file_rpc_create_product_proto_depIdxs = nil
}
